spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  
## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://operation01:3306/car_insure?useUnicode=true&characterEncoding=utf-8
    username: car_insure
    password: car_insure

mybatis:
  mapper-locations: classpath:mybatis/insurance/**/*.xml
  type-aliases-package: cn.rongcapital.operation.microservice.insurance


# 项目单独的配置
insurance:
  #渠道编号
  channelNum: B000003
  #信贷核心接口
  creditCore:
    coreBaseUrl: http://operation03:6001/core/
  coreDealCd:
    loanTrial: Q08001
  productFactoryCd:
    getProducts: QI9901
    getDefValList: QI9902
    getDefVals: QI9903
  #规则引擎地址
  ruleUrl: http://operation01:8085/rule/rule/service/executeChannelIdRule
    #产品工厂地址
  productFactoryUrl: http://operation03:6001/pf/
