server:
 port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 10   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式,如果设置为true，注册的服务下线了，则还在列表中存在
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
        defaultZone: http://admin:admin@eureka1:7001/eureka
        #defaultZone: http://admin:enjoy@eureka1:7001/eureka #,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
  instance: # eureak实例定义
    hostname: eureka1 # 定义 Eureka 实例所在的主机名称
    instance-id: eureka1
    prefer-ip-address: true

spring:
  security:
    user:
      name: admin
      password: admin
  application:
      name: eureka1
  profiles: beta
